### ISSUE TITLE
[Request][Solution Inside] Is it possible to add some top padding when the window not maximized?

### ISSUE THREAD

**Issue by Kooldude93** [sapierens/firefox-edge#14]
I've noticed that on a default FF window some padding is added to the top to make moving it easier. Can this be added back?

**Comment by sapierens** [comment]
I removed it because there wasn't such a padding in Microsoft Edge. Don't think I will be adding it back, unless I see more people actually wanting for that to happen.

However you can restore the padding yourself by searching for
```css
#main-window[sizemode="normal"] #TabsToolbar {
```
and removing the following line
```css
margin-top: -1px !important;
```

It will restore the default Firefox padding behavior.

**Comment by Kooldude93** [comment]
Thanks for this!
